/* 
* Generated by
* 
*      _____ _          __  __      _     _
*     / ____| |        / _|/ _|    | |   | |
*    | (___ | | ____ _| |_| |_ ___ | | __| | ___ _ __
*     \___ \| |/ / _` |  _|  _/ _ \| |/ _` |/ _ \ '__|
*     ____) |   < (_| | | | || (_) | | (_| |  __/ |
*    |_____/|_|\_\__,_|_| |_| \___/|_|\__,_|\___|_|
*
* The code generator that works in many programming languages
*
*			https://www.skaffolder.com
*
*
* You can generate the code from the command-line
*       https://npmjs.com/package/skaffolder-cli
*
*       npm install -g skaffodler-cli
*
*   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *
*
* To remove this comment please upgrade your plan here: 
*      https://app.skaffolder.com/#!/upgrade
*
* Or get up to 70% discount sharing your unique link:
*       https://app.skaffolder.com/#!/register?friend=5e927b1fc4c4454b7744a84b
*
* You will get 10% discount for each one of your friends
* 
*/
// Import Libraries
import { Component, OnInit } from '@angular/core';
import { Location } from '@angular/common';
import { ActivatedRoute } from '@angular/router';
// Import Services
import { ArtService } from '../../services/art.service';
// Import Models
import { Art } from '../../domain/blub_db/art';

// START - USED SERVICES
/**
* artService.create
*	@description CRUD ACTION create
*
* artService.update
*	@description CRUD ACTION update
*	@param ObjectId id Id
*
* artService.get
*	@description CRUD ACTION get
*	@param ObjectId id Id resource
*
*/
// END - USED SERVICES

/**
 * This component allows to edit a Art
 */
@Component({
    selector: 'app-art-edit',
    templateUrl: 'art-edit.component.html',
    styleUrls: ['art-edit.component.css']
})
export class ArtEditComponent implements OnInit {
    item: Art;
    
    model: Art;
    formValid: Boolean;

    constructor(
    private artService: ArtService,
    private route: ActivatedRoute,
    private location: Location) {
        // Init item
        this.item = new Art();
    }

    /**
     * Init
     */
    ngOnInit() {
        this.route.params.subscribe(param => {
            const id: string = param['id'];
            if (id !== 'new') {
                this.artService.get(id).subscribe(item => this.item = item);
            }
            // Get relations
        });
    }


    /**
     * Save Art
     *
     * @param {boolean} formValid Form validity check
     * @param Art item Art to save
     */
    save(formValid: boolean, item: Art): void {
        this.formValid = formValid;
        if (formValid) {
            if (item._id) {
                this.artService.update(item).subscribe(data => this.goBack());
            } else {
                this.artService.create(item).subscribe(data => this.goBack());
            } 
        }
    }

    /**
     * Go Back
     */
    goBack(): void {
        this.location.back();
    }


}



