/* 
* Generated by
* 
*      _____ _          __  __      _     _
*     / ____| |        / _|/ _|    | |   | |
*    | (___ | | ____ _| |_| |_ ___ | | __| | ___ _ __
*     \___ \| |/ / _` |  _|  _/ _ \| |/ _` |/ _ \ '__|
*     ____) |   < (_| | | | || (_) | | (_| |  __/ |
*    |_____/|_|\_\__,_|_| |_| \___/|_|\__,_|\___|_|
*
* The code generator that works in many programming languages
*
*			https://www.skaffolder.com
*
*
* You can generate the code from the command-line
*       https://npmjs.com/package/skaffolder-cli
*
*       npm install -g skaffodler-cli
*
*   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *
*
* To remove this comment please upgrade your plan here: 
*      https://app.skaffolder.com/#!/upgrade
*
* Or get up to 70% discount sharing your unique link:
*       https://app.skaffolder.com/#!/register?friend=5e927b1fc4c4454b7744a84b
*
* You will get 10% discount for each one of your friends
* 
*/
import { Component } from '@angular/core';
import { OnInit } from '@angular/core';
// Import Services
import { ArtService } from '../../services/art.service';
// Import Models
import { Art } from '../../domain/blub_db/art';

// START - USED SERVICES
/**
* artService.delete
*	@description CRUD ACTION delete
*	@param ObjectId id Id
*
* artService.list
*	@description CRUD ACTION list
*
*/
// END - USED SERVICES

/**
 * This component shows a list of Art
 * @class ArtListComponent
 */
@Component({
    selector: 'app-art-list',
    templateUrl: './art-list.component.html',
    styleUrls: ['./art-list.component.css']
})
export class ArtListComponent implements OnInit {
    list: Art[];
    search: any = {};
    idSelected: string;
    constructor(
        private artService: ArtService,
    ) { }

    /**
     * Init
     */
    ngOnInit(): void {
        this.artService.list().subscribe(list => this.list = list);
    }

    /**
     * Select Art to remove
     *
     * @param {string} id Id of the Art to remove
     */
    selectId(id: string) {
        this.idSelected = id;
    }

    /**
     * Remove selected Art
     */
    deleteItem() {
        this.artService.remove(this.idSelected).subscribe(data => this.list = this.list.filter(el => el._id !== this.idSelected));
    }

}
